import type { Product, ParitySummary } from './types';

/**
 * Realistic OmniaStores catalogue — 14 products spanning categories,
 * materials, parity states, stock conditions, and SEO completeness.
 * Designed so the strategist panel has interesting work to do.
 */
export function getCatalogue(): Product[] {
  return [
    {
      id: 'p_cr_925_07',
      master_sku: 'CR-925-07',
      master_title: 'crescent ring',
      display_title: 'Crescent Ring · 925 Silver',
      category: 'Rings',
      material: '925 silver',
      is_limited_edition: false,
      image_hint: 'silver-crescent',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 1_300,
      woocommerce_price_aed: 1_300,
      shopify_qty: 12,
      woocommerce_qty: 8,
      shopify_url: 'https://omniastores.ae/products/crescent-ring',
      woocommerce_url: 'https://omniastores.com/product/crescent-ring',
      parity_status: 'both_match',
      price_delta_pct: 0,
      last_synced_at: '2 min ago',
      seo_title: 'Crescent Ring · 925 Silver — Omnia Dubai Luxury Jewelry',
      seo_description: 'Hand-finished crescent ring in 925 silver. Available in sizes 5-9. Free GCC shipping.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 2, missing_details: [], backlink_keywords: ['crescent ring Dubai', 'silver bridesmaid gift'] },
      metrics: { seen_7d: 1240, bought_7d: 38, searched_7d: 95, bounced_7d: 290, high_bounce_alert: false },
    },
    {
      id: 'p_ms_rg_01',
      master_sku: 'MS-RG-01',
      master_title: 'moonstone pendant',
      display_title: 'Moonstone Pendant · Rose Gold',
      category: 'Necklaces',
      material: 'rose gold',
      is_limited_edition: false,
      image_hint: 'rose-moonstone',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 1_850,
      woocommerce_price_aed: 1_750,
      shopify_qty: 3,
      woocommerce_qty: 6,
      shopify_url: 'https://omniastores.ae/products/moonstone-pendant',
      woocommerce_url: 'https://omniastores.com/product/moonstone-pendant',
      parity_status: 'both_price_drift',
      price_delta_pct: 5.7,
      last_synced_at: '2 min ago',
      seo_title: 'Moonstone Pendant Rose Gold — Omnia Luxury',
      seo_description: 'Moonstone pendant in rose gold.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 5, missing_details: ['stone clarity grade', 'chain length'], backlink_keywords: [] },
      metrics: { seen_7d: 870, bought_7d: 24, searched_7d: 71, bounced_7d: 210, high_bounce_alert: false },
    },
    {
      id: 'p_sd_bl_01',
      master_sku: 'SD-BL-01',
      master_title: 'sapphire drop earrings',
      display_title: 'Sapphire Drop Earrings',
      category: 'Earrings',
      material: '18k gold',
      is_limited_edition: false,
      image_hint: 'blue-sapphire',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 2_300,
      woocommerce_price_aed: 2_300,
      shopify_qty: 9,
      woocommerce_qty: 4,
      shopify_url: 'https://omniastores.ae/products/sapphire-drop-earrings',
      woocommerce_url: 'https://omniastores.com/product/sapphire-drop-earrings',
      parity_status: 'both_match',
      price_delta_pct: 0,
      last_synced_at: '2 min ago',
      seo_title: null,
      seo_description: null,
      seo_status: 'pending',
      google_shopping_status: 'pending',
      ai_audit_notes: { weakness_score: 8, missing_details: ['stone clarity', 'metal weight', 'high-res image refs'], backlink_keywords: [] },
      metrics: { seen_7d: 612, bought_7d: 14, searched_7d: 88, bounced_7d: 320, high_bounce_alert: true },
    },
    {
      id: 'p_ps_18_01',
      master_sku: 'PS-18-01',
      master_title: 'pearl strand necklace',
      display_title: 'Pearl Strand Necklace · 18"',
      category: 'Necklaces',
      material: 'pearl',
      is_limited_edition: false,
      image_hint: 'white-pearl',
      on_shopify: false,
      on_woocommerce: true,
      shopify_price_aed: null,
      woocommerce_price_aed: 2_450,
      shopify_qty: null,
      woocommerce_qty: 11,
      shopify_url: null,
      woocommerce_url: 'https://omniastores.com/product/pearl-strand',
      parity_status: 'woocommerce_only',
      price_delta_pct: null,
      last_synced_at: '2 min ago',
      seo_title: 'Pearl Strand Necklace 18 inch — Omnia',
      seo_description: 'Classic 18-inch pearl strand necklace.',
      seo_status: 'optimized',
      google_shopping_status: 'pending',
      ai_audit_notes: { weakness_score: 4, missing_details: ['pearl grade'], backlink_keywords: [] },
      metrics: { seen_7d: 410, bought_7d: 18, searched_7d: 44, bounced_7d: 150, high_bounce_alert: false },
    },
    {
      id: 'p_et_925_01',
      master_sku: 'ET-925-01',
      master_title: 'emerald tennis bracelet',
      display_title: 'Emerald Tennis Bracelet · 925',
      category: 'Bracelets',
      material: '925 silver',
      is_limited_edition: false,
      image_hint: 'green-emerald',
      on_shopify: true,
      on_woocommerce: false,
      shopify_price_aed: 2_800,
      woocommerce_price_aed: null,
      shopify_qty: 7,
      woocommerce_qty: null,
      shopify_url: 'https://omniastores.ae/products/emerald-tennis-bracelet',
      woocommerce_url: null,
      parity_status: 'shopify_only',
      price_delta_pct: null,
      last_synced_at: '2 min ago',
      seo_title: 'Emerald Tennis Bracelet 925 Silver — Omnia',
      seo_description: 'Emerald tennis bracelet in 925 silver, hand-set in Dubai.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 3, missing_details: [], backlink_keywords: ['tennis bracelet GCC'] },
      metrics: { seen_7d: 580, bought_7d: 12, searched_7d: 62, bounced_7d: 175, high_bounce_alert: false },
    },
    {
      id: 'p_rb_gd_02',
      master_sku: 'RB-GD-02',
      master_title: 'ruby bangle',
      display_title: 'Ruby Bangle · Gold-Plated',
      category: 'Bracelets',
      material: 'gold-plated',
      is_limited_edition: false,
      image_hint: 'red-ruby',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 950,
      woocommerce_price_aed: 1_100,
      shopify_qty: 14,
      woocommerce_qty: 0,
      shopify_url: 'https://omniastores.ae/products/ruby-bangle',
      woocommerce_url: 'https://omniastores.com/product/ruby-bangle',
      parity_status: 'both_price_drift',
      price_delta_pct: -13.6,
      last_synced_at: '2 min ago',
      seo_title: 'Ruby Bangle Gold-Plated — Omnia',
      seo_description: 'Hand-crafted ruby bangle.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 6, missing_details: ['ruby treatment disclosure'], backlink_keywords: [] },
      metrics: { seen_7d: 720, bought_7d: 19, searched_7d: 55, bounced_7d: 190, high_bounce_alert: false },
    },
    {
      id: 'p_oe_sl_01',
      master_sku: 'OE-SL-01',
      master_title: 'opal earrings',
      display_title: 'Opal Stud Earrings · Silver',
      category: 'Earrings',
      material: '925 silver',
      is_limited_edition: false,
      image_hint: 'opal-iridescent',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 740,
      woocommerce_price_aed: 720,
      shopify_qty: 0,
      woocommerce_qty: 5,
      shopify_url: 'https://omniastores.ae/products/opal-studs',
      woocommerce_url: 'https://omniastores.com/product/opal-studs',
      parity_status: 'both_price_drift',
      price_delta_pct: 2.8,
      last_synced_at: '2 min ago',
      seo_title: null,
      seo_description: null,
      seo_status: 'pending',
      google_shopping_status: 'pending',
      ai_audit_notes: { weakness_score: 9, missing_details: ['origin', 'opal type', 'image refs'], backlink_keywords: [] },
      metrics: { seen_7d: 290, bought_7d: 3, searched_7d: 41, bounced_7d: 145, high_bounce_alert: false },
    },
    {
      id: 'p_cn_gd_le',
      master_sku: 'CN-GD-LE',
      master_title: 'celestial necklace limited',
      display_title: 'Celestial Necklace · LE 2026',
      category: 'Necklaces',
      material: '18k gold',
      is_limited_edition: true,
      image_hint: 'gold-celestial',
      on_shopify: true,
      on_woocommerce: false,
      shopify_price_aed: 4_900,
      woocommerce_price_aed: null,
      shopify_qty: 2,
      woocommerce_qty: null,
      shopify_url: 'https://omniastores.ae/products/celestial-necklace-le',
      woocommerce_url: null,
      parity_status: 'shopify_only',
      price_delta_pct: null,
      last_synced_at: '2 min ago',
      seo_title: 'Celestial Necklace LE 2026 — Omnia Limited Edition',
      seo_description: 'Limited Edition celestial necklace in 18k gold. Only 50 pieces. Numbered & certified.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 2, missing_details: [], backlink_keywords: ['limited edition Dubai jewelry'] },
      metrics: { seen_7d: 1820, bought_7d: 48, searched_7d: 142, bounced_7d: 340, high_bounce_alert: false },
    },
    {
      id: 'p_br_gd_01',
      master_sku: 'BR-GD-01',
      master_title: 'bridal set tier 1',
      display_title: 'Omnia Bridal Set · Tier I',
      category: 'Bridal Sets',
      material: '18k gold + diamond',
      is_limited_edition: false,
      image_hint: 'bridal-gold',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 8_400,
      woocommerce_price_aed: 8_400,
      shopify_qty: 6,
      woocommerce_qty: 3,
      shopify_url: 'https://omniastores.ae/products/bridal-set-tier-1',
      woocommerce_url: 'https://omniastores.com/product/bridal-set-tier-1',
      parity_status: 'both_match',
      price_delta_pct: 0,
      last_synced_at: '2 min ago',
      seo_title: 'Omnia Bridal Set Tier I — 18k Gold + Diamond',
      seo_description: 'Complete bridal jewelry set in 18k gold with certified diamonds. Crafted in Dubai.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 3, missing_details: ['diamond clarity grade'], backlink_keywords: ['Dubai bridal jewelry', 'GCC wedding sets'] },
      metrics: { seen_7d: 940, bought_7d: 7, searched_7d: 220, bounced_7d: 260, high_bounce_alert: false },
    },
    {
      id: 'p_dt_18_01',
      master_sku: 'DT-18-01',
      master_title: 'diamond tennis necklace',
      display_title: 'Diamond Tennis Necklace · 18k',
      category: 'Necklaces',
      material: '18k gold + diamond',
      is_limited_edition: false,
      image_hint: 'diamond-tennis',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 6_900,
      woocommerce_price_aed: 7_400,
      shopify_qty: 4,
      woocommerce_qty: 2,
      shopify_url: 'https://omniastores.ae/products/diamond-tennis',
      woocommerce_url: 'https://omniastores.com/product/diamond-tennis',
      parity_status: 'both_price_drift',
      price_delta_pct: -6.8,
      last_synced_at: '2 min ago',
      seo_title: 'Diamond Tennis Necklace 18k Gold — Omnia',
      seo_description: 'Lab-grown diamond tennis necklace in 18k gold. GRA-certified.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 4, missing_details: ['certificate scan'], backlink_keywords: ['lab grown diamond GCC'] },
      metrics: { seen_7d: 780, bought_7d: 9, searched_7d: 110, bounced_7d: 215, high_bounce_alert: false },
    },
    {
      id: 'p_ax_sl_01',
      master_sku: 'AX-SL-01',
      master_title: 'anklet silver',
      display_title: 'Whisper Anklet · 925 Silver',
      category: 'Bracelets',
      material: '925 silver',
      is_limited_edition: false,
      image_hint: 'silver-anklet',
      on_shopify: false,
      on_woocommerce: true,
      shopify_price_aed: null,
      woocommerce_price_aed: 460,
      shopify_qty: null,
      woocommerce_qty: 24,
      shopify_url: null,
      woocommerce_url: 'https://omniastores.com/product/whisper-anklet',
      parity_status: 'woocommerce_only',
      price_delta_pct: null,
      last_synced_at: '2 min ago',
      seo_title: null,
      seo_description: null,
      seo_status: 'pending',
      google_shopping_status: 'pending',
      ai_audit_notes: { weakness_score: 7, missing_details: ['length range', 'clasp type'], backlink_keywords: [] },
      metrics: { seen_7d: 220, bought_7d: 11, searched_7d: 35, bounced_7d: 70, high_bounce_alert: false },
    },
    {
      id: 'p_fc_le_01',
      master_sku: 'FC-LE-01',
      master_title: 'founder crescent limited',
      display_title: 'Founder Crescent · LE 2025',
      category: 'Rings',
      material: '18k gold + diamond',
      is_limited_edition: true,
      image_hint: 'founder-gold',
      on_shopify: true,
      on_woocommerce: false,
      shopify_price_aed: 18_400,
      woocommerce_price_aed: null,
      shopify_qty: 0,
      woocommerce_qty: null,
      shopify_url: 'https://omniastores.ae/products/founder-crescent-le',
      woocommerce_url: null,
      parity_status: 'shopify_only',
      price_delta_pct: null,
      last_synced_at: '2 min ago',
      seo_title: 'Founder Crescent LE 2025 — Sold Out',
      seo_description: 'The Founder Series Crescent — 12 pieces, numbered. Sold out.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 2, missing_details: [], backlink_keywords: ['Omnia Founder Series'] },
      metrics: { seen_7d: 410, bought_7d: 0, searched_7d: 88, bounced_7d: 95, high_bounce_alert: false },
    },
    {
      id: 'p_ec_pl_01',
      master_sku: 'EC-PL-01',
      master_title: 'eternity choker',
      display_title: 'Eternity Choker · Platinum-Tone',
      category: 'Necklaces',
      material: 'platinum-tone',
      is_limited_edition: false,
      image_hint: 'choker-platinum',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 1_650,
      woocommerce_price_aed: 1_590,
      shopify_qty: 8,
      woocommerce_qty: 12,
      shopify_url: 'https://omniastores.ae/products/eternity-choker',
      woocommerce_url: 'https://omniastores.com/product/eternity-choker',
      parity_status: 'both_price_drift',
      price_delta_pct: 3.8,
      last_synced_at: '2 min ago',
      seo_title: null,
      seo_description: null,
      seo_status: 'pending',
      google_shopping_status: 'pending',
      ai_audit_notes: { weakness_score: 8, missing_details: ['plating durability', 'sizing chart'], backlink_keywords: [] },
      metrics: { seen_7d: 510, bought_7d: 6, searched_7d: 79, bounced_7d: 245, high_bounce_alert: true },
    },
    {
      id: 'p_ah_18_01',
      master_sku: 'AH-18-01',
      master_title: 'arabian heritage ring',
      display_title: 'Arabian Heritage Ring · 18k',
      category: 'Rings',
      material: '18k gold',
      is_limited_edition: false,
      image_hint: 'heritage-gold',
      on_shopify: true,
      on_woocommerce: true,
      shopify_price_aed: 3_200,
      woocommerce_price_aed: 3_200,
      shopify_qty: 5,
      woocommerce_qty: 3,
      shopify_url: 'https://omniastores.ae/products/heritage-ring',
      woocommerce_url: 'https://omniastores.com/product/heritage-ring',
      parity_status: 'both_match',
      price_delta_pct: 0,
      last_synced_at: '2 min ago',
      seo_title: 'Arabian Heritage Ring 18k Gold — Omnia',
      seo_description: 'Heritage-inspired ring in 18k gold. Hand-engraved in Dubai.',
      seo_status: 'optimized',
      google_shopping_status: 'listed',
      ai_audit_notes: { weakness_score: 3, missing_details: [], backlink_keywords: ['heritage GCC jewelry'] },
      metrics: { seen_7d: 380, bought_7d: 8, searched_7d: 52, bounced_7d: 110, high_bounce_alert: false },
    },
  ];
}

export function getParitySummary(): ParitySummary {
  const rows = getCatalogue();
  return {
    total: rows.length,
    both_match: rows.filter((r) => r.parity_status === 'both_match').length,
    both_price_drift: rows.filter((r) => r.parity_status === 'both_price_drift').length,
    shopify_only: rows.filter((r) => r.parity_status === 'shopify_only').length,
    woocommerce_only: rows.filter((r) => r.parity_status === 'woocommerce_only').length,
    low_stock: rows.filter(
      (r) =>
        (r.shopify_qty !== null && r.shopify_qty <= 3) ||
        (r.woocommerce_qty !== null && r.woocommerce_qty <= 3),
    ).length,
    limited_editions: rows.filter((r) => r.is_limited_edition).length,
    needs_seo: rows.filter((r) => r.seo_status === 'pending').length,
    needs_shopping_list: rows.filter((r) => r.google_shopping_status === 'pending').length,
    last_run: '2 min ago',
    next_run: 'in 28 min',
    source: 'hex',
  };
}
